apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: todo-app-prod
type: Opaque
data:
  # This should be base64 encoded in production
  url: <BASE64_ENCODED_DATABASE_URL>
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: todo-app-prod
type: Opaque
data:
  # This should be base64 encoded in production
  secret: <BASE64_ENCODED_AUTH_SECRET>