apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  api-base-url: {{ .Values.config.apiBaseUrl | quote }}