{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default "todo-app-prod" }}
  labels:
    name: {{ .Values.namespace.name | default "todo-app-prod" }}
{{- end }}